"""initial migration

Revision ID: f24155fe7415
Revises:
Create Date: 2021-09-29 23:23:02.272300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Numeric


# revision identifiers, used by Alembic.
revision = 'f24155fe7415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('image_id', sa.String(length=32), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('card_number', sa.String(
                        length=20), nullable=True),
                    sa.Column('card_expiry', sa.String(
                        length=5), nullable=True),
                    sa.Column('card_cvc', sa.String(length=4), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('image_id', sa.String(length=32), nullable=True),
                    sa.Column('price', sa.Numeric(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('price', sa.Numeric(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    category = table('categories',
                     column('id', Integer),
                     column('name', String),
                     column('image_id', String),
                     )
    items = table('items',
                  column('id', Integer),
                  column('name', String),
                  column('image_id', String),
                  column('price', Numeric),
                  column('category_id', String),
                  )

    op.bulk_insert(category,
                   [
                       {
                           "id": 1,
                           "image_id": "f3fbf57b118fa9",
                           "name": "Bakery"
                       },
                       {
                           "id": 2,
                           "image_id": "b271afbefdc554",
                           "name": "Entrees"
                       },
                       {
                           "id": 3,
                           "image_id": "eba73b2361fae3",
                           "name": "Drinks"
                       }
                   ]
                   )

    op.bulk_insert(items,
                   [
                       {
                           "category_id": 1,
                           "id": 1,
                           "image_id": "293202f9d9f7f4",
                           "name": "Bagel",
                           "price": 2.0
                       },
                       {
                           "category_id": 1,
                           "id": 2,
                           "image_id": "808916fd5ddf96",
                           "name": "Croissant",
                           "price": 1.0
                       },
                       {
                           "category_id": 1,
                           "id": 3,
                           "image_id": "95d02a230fe050",
                           "name": "Muffin",
                           "price": 1.25
                       },
                       {
                           "category_id": 1,
                           "id": 4,
                           "image_id": "23f95765b967ff",
                           "name": "Toast / Bread",
                           "price": 1
                       },
                       {
                           "category_id": 1,
                           "id": 5,
                           "image_id": "5650be5d48a99b",
                           "name": "English Muffin",
                           "price": 2.5
                       },
                       {
                           "category_id": 2,
                           "id": 6,
                           "image_id": "bd237a0c0d19ef",
                           "name": "Pasta Bar",
                           "price": 12.99
                       },
                       {
                           "category_id": 2,
                           "id": 7,
                           "image_id": "3e1bd1342800f7",
                           "name": "Mediterranean Entree",
                           "price": 10.99
                       },
                       {
                           "category_id": 2,
                           "id": 8,
                           "image_id": "72589c4c990f97",
                           "name": "Indian Entree",
                           "price": 11.95
                       },
                       {
                           "category_id": 3,
                           "id": 9,
                           "image_id": "70c2a6247e7b58",
                           "name": "Small Drink",
                           "price": 0.75
                       },
                       {
                           "category_id": 3,
                           "id": 10,
                           "image_id": "dba0fc03da30ca",
                           "name": "Medium Drink",
                           "price": 1.5
                       },
                       {
                           "category_id": 3,
                           "id": 11,
                           "image_id": "ffc9bf61e441cd",
                           "name": "Large Drink",
                           "price": 2
                       }
                   ]
                   )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('items')
    op.drop_table('orders')
    op.drop_table('categories')
    # ### end Alembic commands ###
